name    'puppet-rsnapshot'
version '0.0.1'
source 'UNKNOWN'
author 'Loic Dachary'
license 'AGPLv3+'
source 'http://redmine.the.re/git/puppet-rsnapshot.git'
summary 'rsnapshot module'
description 'rsnapshot module for Debian'
project_page 'http://redmine.the.re/projects/puppet-rsnapshot'
#dependency 'dhoppe/puppet', '>=0.0.1'
